AllCops:
  TargetRubyVersion: 3.4

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
